---
name: Docker Image CI

on:
  push:
    branches: 
      - '**'
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and tag the docker image 
      run: |
        DATETAG=$(date +%s)
        docker build . --file Dockerfile --tag alecbrown/rust-wrangler:$DATETAG
        docker image tag alecbrown/rust-wrangler:$DATETAG alecbrown/rust-wrangler:latest

    - name: Push the Docker Image to hub.docker.com
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}
        docker push --all-tags alecbrown/rust-wrangler
